# Generated by Django 2.0.4 on 2018-04-20 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUrlParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_cyberleninka', models.URLField(max_length=600)),
                ('url_scholar', models.URLField(max_length=600)),
                ('url_socio', models.URLField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taccess', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DirAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirname', models.CharField(max_length=25)),
                ('permissions', models.IntegerField(choices=[(1, 'чтение'), (2, 'запись'), (3, 'чтение и запись'), (4, 'удаление'), (7, 'чтение, запись и удаление')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к директории',
                'verbose_name_plural': 'Доступ к директории',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_url', models.FilePathField(max_length=600)),
                ('net_url', models.URLField(max_length=600)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('keywords', models.CharField(default='', max_length=255)),
                ('year1', models.CharField(default='', max_length=4)),
                ('year2', models.CharField(default='', max_length=4)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='user_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artman.UserQuery'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artman.Document'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baseurlparser',
            name='user_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artman.UserQuery'),
        ),
    ]
