# Generated by Django 2.0.4 on 2018-04-23 15:04

import artman.models_anton
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artman', '0002_remove_document_user_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='local_url',
            field=models.FileField(max_length=600, upload_to=artman.models_anton.upload_path),
        ),
    ]
