# Generated by Django 2.0.4 on 2018-05-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artman', '0007_auto_20180505_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupilsrequest',
            old_name='result',
            new_name='status',
        ),
    ]
